# coding: utf-8

# flake8: noqa
"""
    Unity Processing API conforming to the OGC API - Processes - Part 1 standard

    This document is an API definition document provided alongside the OGC API - Processes standard. The OGC API - Processes Standard specifies a processing interface to communicate over a RESTful protocol using JavaScript Object Notation (JSON) encodings. The specification allows for the wrapping of computational tasks into executable processes that can be offered by a server and be invoked by a client application.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from unity_sps_ogc_processes_api_python_client.models.bbox import Bbox
from unity_sps_ogc_processes_api_python_client.models.conf_classes import ConfClasses
from unity_sps_ogc_processes_api_python_client.models.crs import Crs
from unity_sps_ogc_processes_api_python_client.models.crs5 import Crs5
from unity_sps_ogc_processes_api_python_client.models.exception import Exception
from unity_sps_ogc_processes_api_python_client.models.execute import Execute
from unity_sps_ogc_processes_api_python_client.models.health_check import HealthCheck
from unity_sps_ogc_processes_api_python_client.models.http_validation_error import (
    HTTPValidationError,
)
from unity_sps_ogc_processes_api_python_client.models.input_value_input import (
    InputValueInput,
)
from unity_sps_ogc_processes_api_python_client.models.input_value_no_object_input import (
    InputValueNoObjectInput,
)
from unity_sps_ogc_processes_api_python_client.models.input_value_no_object_output import (
    InputValueNoObjectOutput,
)
from unity_sps_ogc_processes_api_python_client.models.input_value_output import (
    InputValueOutput,
)
from unity_sps_ogc_processes_api_python_client.models.job_control_options import (
    JobControlOptions,
)
from unity_sps_ogc_processes_api_python_client.models.job_list import JobList
from unity_sps_ogc_processes_api_python_client.models.landing_page import LandingPage
from unity_sps_ogc_processes_api_python_client.models.link import Link
from unity_sps_ogc_processes_api_python_client.models.metadata import Metadata
from unity_sps_ogc_processes_api_python_client.models.metadata1 import Metadata1
from unity_sps_ogc_processes_api_python_client.models.metadata2 import Metadata2
from unity_sps_ogc_processes_api_python_client.models.process_input import ProcessInput
from unity_sps_ogc_processes_api_python_client.models.process_list import ProcessList
from unity_sps_ogc_processes_api_python_client.models.process_output import (
    ProcessOutput,
)
from unity_sps_ogc_processes_api_python_client.models.process_summary import (
    ProcessSummary,
)
from unity_sps_ogc_processes_api_python_client.models.status_code import StatusCode
from unity_sps_ogc_processes_api_python_client.models.status_info import StatusInfo
from unity_sps_ogc_processes_api_python_client.models.subscriber import Subscriber
from unity_sps_ogc_processes_api_python_client.models.validation_error import (
    ValidationError,
)
from unity_sps_ogc_processes_api_python_client.models.validation_error_loc_inner import (
    ValidationErrorLocInner,
)
from unity_sps_ogc_processes_api_python_client.models.value import Value
