# coding: utf-8

"""
    Unity Processing API conforming to the Draft of OGC API - Processes - Part 2: Deploy, Replace, Undeploy

    This document is an API definition document provided alongside the OGC API - Processes standard. The OGC API - Processes Standard specifies a processing interface to communicate over a RESTful protocol using JavaScript Object Notation (JSON) encodings. The specification allows for the wrapping of computational tasks into executable processes that can be offered by a server and be invoked by a client application.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unity_sps_ogc_processes_api_python_client.models.execution_unit import (
    ExecutionUnit,
)


class TestExecutionUnit(unittest.TestCase):
    """ExecutionUnit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExecutionUnit:
        """Test ExecutionUnit
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `ExecutionUnit`
        """
        model = ExecutionUnit()
        if include_optional:
            return ExecutionUnit(
                type = '',
                image = '',
                deployment = '',
                config = unity_sps_ogc_processes_api_python_client.models.execution_unit_config.ExecutionUnitConfig(
                    cpu_min = null,
                    cpu_max = null,
                    memory_min = null,
                    memory_max = null,
                    storage_temp_min = null,
                    storage_outputs_min = null,
                    job_timeout = null,
                    additional_properties = unity_sps_ogc_processes_api_python_client.models.additional_properties.Additional Properties(), ),
                additional_properties = unity_sps_ogc_processes_api_python_client.models.additional_properties.Additional Properties()
            )
        else:
            return ExecutionUnit(
                type = '',
                image = '',
        )
        """

    def testExecutionUnit(self):
        """Test ExecutionUnit"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
