# coding: utf-8

"""
    Unity Processing API conforming to the Draft of OGC API - Processes - Part 2: Deploy, Replace, Undeploy

    This document is an API definition document provided alongside the OGC API - Processes standard. The OGC API - Processes Standard specifies a processing interface to communicate over a RESTful protocol using JavaScript Object Notation (JSON) encodings. The specification allows for the wrapping of computational tasks into executable processes that can be offered by a server and be invoked by a client application.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unity_sps_ogc_processes_api_python_client.api.jobs_api import JobsApi


class TestJobsApi(unittest.TestCase):
    """JobsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = JobsApi()

    def tearDown(self) -> None:
        pass

    def test_dismiss_jobs_job_id_delete(self) -> None:
        """Test case for dismiss_jobs_job_id_delete

        cancel a job execution, remove a finished job
        """
        pass

    def test_get_jobs_jobs_get(self) -> None:
        """Test case for get_jobs_jobs_get

        retrieve the list of jobs.
        """
        pass

    def test_get_result_jobs_job_id_results_get(self) -> None:
        """Test case for get_result_jobs_job_id_results_get

        retrieve the result(s) of a job
        """
        pass

    def test_get_status_jobs_job_id_get(self) -> None:
        """Test case for get_status_jobs_job_id_get

        retrieve the status of a job
        """
        pass


if __name__ == "__main__":
    unittest.main()
