# coding: utf-8

"""
    Unity Processing API conforming to the OGC API - Processes - Part 1 standard

    This document is an API definition document provided alongside the OGC API - Processes standard. The OGC API - Processes Standard specifies a processing interface to communicate over a RESTful protocol using JavaScript Object Notation (JSON) encodings. The specification allows for the wrapping of computational tasks into executable processes that can be offered by a server and be invoked by a client application.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest


class TestCrs5(unittest.TestCase):
    """Crs5 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCrs5(self):
        """Test Crs5"""
        # inst = Crs5()


if __name__ == "__main__":
    unittest.main()
