# coding: utf-8

"""
    Unity Processing API conforming to the OGC API - Processes - Part 1 standard

    This document is an API definition document provided alongside the OGC API - Processes standard. The OGC API - Processes Standard specifies a processing interface to communicate over a RESTful protocol using JavaScript Object Notation (JSON) encodings. The specification allows for the wrapping of computational tasks into executable processes that can be offered by a server and be invoked by a client application.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
from enum import Enum

from typing_extensions import Self


class Crs5(str, Enum):
    """
    Crs5
    """

    """
    allowed enum values
    """
    HTTP_COLON_SLASH_SLASH_WWW_DOT_OPENGIS_DOT_NET_SLASH_DEF_SLASH_CRS_SLASH_OGC_SLASH_1_DOT_3_SLASH_CRS84 = (
        "http://www.opengis.net/def/crs/OGC/1.3/CRS84"
    )
    HTTP_COLON_SLASH_SLASH_WWW_DOT_OPENGIS_DOT_NET_SLASH_DEF_SLASH_CRS_SLASH_OGC_SLASH_0_SLASH_CRS84H = (
        "http://www.opengis.net/def/crs/OGC/0/CRS84h"
    )

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Crs5 from a JSON string"""
        return cls(json.loads(json_str))
